### PR TITLE
Fixing type errors

### PR DESCRIPTION
**Pull request by donker**
Fixing a number of errors in the typescript file

### CODE REVIEW

**Comment by iJungleboy** [comment]
@ropalko please check
@donker please not that our coding conventions use single quotes, not double, and I believe many changes are simply because of quoting.

**Comment by donker** [comment]
OK, I'm using Prettier in VS Code which prefers the double quotes. But most changes are for null checks. If you leave strict type checking on then TS will tell you many element lookups may result in null.

**Comment by iJungleboy** [comment]
@ropalko this is a bit older, but could you check. wey may hav ealready done much of this, but I don't know. 

then pls close or whatever is reasonable.

**Comment by ropalko** [comment]
fixed in new release ([05.00.04](https://github.com/2sic/dnn-theme-2shine-bs5/tree/05.00.04))

**Pull request closed without merging**
